name: CI

on:
  push: {branches: master}
  pull_request: {branches: master}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: actions/setup-elixir@1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - run: mix deps.get
      - run: mix test --trace
      - run: mix format --check-formatted