name: CI

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - otp: 21.x
            elixir: 1.8.x
          - otp: 21.x
            elixir: 1.9.x
          - otp: 21.x
            elixir: 1.10.x
          - otp: 21.x
            elixir: 1.11.x
          - otp: 22.x
            elixir: 1.12.x
          - otp: 22.x
            elixir: 1.13.x
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - uses: erlef/setup-elixir@988e02bfe678367a02564f65ca2e37726dc0268f # v1.9.0
        with:
          otp-version: 21.x
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@67b6d52d50609f6166e3ea1d8872aca3a4763bd2 # v2.1.7
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: crash-logs
          path: erl_crash.dump
          if-no-files-found: ignore
      - run: mix deps.get
      - run: mix test --trace
      - run: mix format --check-formatted
